In [38]:
#이 파일은 k_center.py 모듈이 잘 돌아가는지 확인하기 위함. 확인이 끝나면 삭제하겠습니다.

In [2]:
from k_center import Kcenter,Set_handle
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# 이미지 수 110개와 73개, 임베딩 벡터 크기 10
# center의 최대 반지름이 threshold 보다 작도록 k-center 구하기
vec_set1 = np.random.randn(110,10) 
vec_set2 = np.random.randn(73,10)
vec_set3 = np.random.randn(23,10)
vec_set4 = np.random.randn(323,10)
set_coll = [vec_set1,vec_set2, vec_set3, vec_set4]

kt = Kcenter(set_coll)
kw = kt.distance_matrix(method="bhattacharyya_distance")
print(kw)
aa,bb = kt.selectKcenter(threshold= 0.4)
print(aa)
print(bb)
"""
1. class set 간 거리 행렬 만들기
2. 거리행렬을 기반으로 Kcenter 만들기
"""

현재 클러스터링 거리 함수는 bhattacharyya_distance
기준 0 표적 0 거리: 0.0
기준 0 표적 1 거리: 0.21691560110668848
기준 0 표적 2 거리: 0.4990246167611945
기준 0 표적 3 거리: 0.09450097343792678
기준 1 표적 0 거리: 0.21691560110668848
기준 1 표적 1 거리: 0.0
기준 1 표적 2 거리: 0.5595887445098926
기준 1 표적 3 거리: 0.11507339214003263
기준 2 표적 0 거리: 0.4990246167611945
기준 2 표적 1 거리: 0.5595887445098926
기준 2 표적 2 거리: 0.0
기준 2 표적 3 거리: 0.48003052874538565
기준 3 표적 0 거리: 0.09450097343792678
기준 3 표적 1 거리: 0.11507339214003263
기준 3 표적 2 거리: 0.48003052874538565
기준 3 표적 3 거리: 0.0
(4, 4)
[[0.         0.2169156  0.49902462 0.09450097]
 [0.2169156  0.         0.55958874 0.11507339]
 [0.49902462 0.55958874 0.         0.48003053]
 [0.09450097 0.11507339 0.48003053 0.        ]]
2 1 {0: 1, 1: 1, 2: 2, 3: 1}
[0.21691560110668848, 0.0, 0.0, 0.11507339214003263]


'\n1. class set 간 거리 행렬 만들기\n2. 거리행렬을 기반으로 Kcenter 만들기\n'

# 정규분포 샘플을 만들어서 각 거리를 구해서 평균과 표준편차와 거리의 관계를 유추해보자

In [18]:
vec_set1 = 3.0*np.random.randn(5000,100) + 2.0
vec_set2 = 3.0*np.random.randn(5000,100) + 6.0
vec_set3 = 5.0*np.random.randn(5000,100) + 2.0
vec_set4 = 5.0*np.random.randn(5000,100) +6.0
vec_set5 = 4.0*np.random.randn(5000,100) +4.0
set_coll = [vec_set1,vec_set2, vec_set3, vec_set4, vec_set5]

kt = Kcenter(set_coll)
kb = kt.distance_matrix(method="bhattacharyya_distance")
print(kb)


현재 클러스터링 거리 함수는 bhattacharyya_distance
(5, 5)
[[ 0.         22.63522678  6.43507148 17.9661638   6.26009276]
 [22.63522678  0.         18.47266764  6.4614204   6.28717952]
 [ 6.43507148 18.47266764  0.          8.21252575  3.94291099]
 [17.9661638   6.4614204   8.21252575  0.          3.88131077]
 [ 6.26009276  6.28717952  3.94291099  3.88131077  0.        ]]


In [19]:
kh = kt.distance_matrix(method="hellinger_distance")
print(kh)

현재 클러스터링 거리 함수는 hellinger_distance
weights의 shape은 (5, 5)
[[1.05367121e-08 1.00000000e+00 9.99197531e-01 9.99999992e-01
  9.99044009e-01]
 [1.00000000e+00 1.05367121e-08 9.99999995e-01 9.99218407e-01
  9.99069568e-01]
 [9.99197531e-01 9.99999995e-01 0.00000000e+00 9.99864373e-01
  9.90256692e-01]
 [9.99999992e-01 9.99218407e-01 9.99864373e-01 1.05367121e-08
  9.89634390e-01]
 [9.99044009e-01 9.99069568e-01 9.90256692e-01 9.89634390e-01
  1.49011612e-08]]


In [20]:
kk = kt.distance_matrix(method="kullback_leibler_divergence")
print(kk)

현재 클러스터링 거리 함수는 kullback_leibler_divergence
(5, 5)
[[ 0.00000000e+00  9.34670711e+01  1.93932221e+01  5.09239857e+01
   2.01152912e+01]
 [ 8.96344910e+01  0.00000000e+00  5.23965194e+01  1.94674397e+01
   1.99950762e+01]
 [ 4.04998653e+01  1.32385421e+02  0.00000000e+00  3.23690645e+01
   1.99682026e+01]
 [ 1.29272359e+02  4.06860629e+01  3.39712977e+01  0.00000000e+00
   2.00461965e+01]
 [ 3.40628185e+01  3.48414477e+01  1.32104703e+01  1.28396723e+01
  -7.10542736e-15]]


In [40]:
vec_set1 = np.random.randn(110,10) 
vec_set2 = np.random.randn(73,10) 
set_ds = Set_handle(vec_set1, vec_set2)
rand_pois = np.random.poisson(lam=20, size=(43,10))


In [41]:
set_ds.hellinger_distance()

0.40545125159972695

In [42]:
from scipy.stats import shapiro

print("정규",shapiro(vec_set1)) #p-value가 0.05이상이기 때문에 95%의 확률로 데이터는 정규성을 가진다.
print("포아송",shapiro(rand_pois)) # 0.05 미만이기 때문에 정규성 기각

정규 ShapiroResult(statistic=0.9992696046829224, pvalue=0.956469714641571)
포아송 ShapiroResult(statistic=0.9879574179649353, pvalue=0.0012799291871488094)


# 논리적 문제점 없는지 확인 with Cifar-100

# 모델의 분류 성능 확인

In [1]:
import torch
import torchvision
import torchvision.transforms as transforms
import torch.optim as optim



In [24]:
transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

batch_size = 4

trainset = torchvision.datasets.CIFAR10(root='./data', train=True,
                                        download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=batch_size,
                                          shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False,
                                       download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=batch_size,
                                         shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat',
           'deer', 'dog', 'frog', 'horse', 'ship', 'truck')


Files already downloaded and verified
Files already downloaded and verified


In [39]:
import os
import torch
from torch import nn
import timm

class Baseline(nn.Module):
    def __init__(self, loss_fn):
        super(Baseline, self).__init__()
        self.loss_fn = loss_fn
        self.patch_embedding = None
        self.embedding = None
        self.fc = None

    def forward(self, images):
        return self.fc(self.embedding(self.patch_embedding(images)))

    def predict(self, images):
        return nn.Softmax(dim=-1)(self(images))

    def train_step(self, images, y_true, optimizer, lr_scheduler=None):
        images = images.to(next(self.parameters()).device)
        y_true = y_true.to(next(self.parameters()).device)

        optimizer.zero_grad()
        y_pred = self(images) #self.fc(self.embedding(images))
        
        loss_f = self.loss_fn()
        loss = loss_f(y_pred, y_true)

        loss.backward()
        optimizer.step()
        if lr_scheduler is not None:
            lr_scheduler.step()
        return loss, y_pred

    def test_step(self, images, y_true):
        images = images.to(next(self.parameters()).device)
        y_true = y_true.to(next(self.parameters()).device)

        with torch.no_grad():
            y_pred = self(images) #self.fc(self.embedding(images))
            loss = self.loss_fn(y_pred, y_true)
        return loss, y_pred

    def save(self, epoch, path_to_pt, optimizer=None):
        dir = os.path.dirname(path_to_pt)
        if not os.path.exists(dir):
            os.makedirs(dir)
        d = {'epoch': epoch,
            'patch_embedding': self.patch_embedding.state_dict(),
            'fc' : self.fc.state_dict()}
        if optimizer is not None:
            d['optimizer'] = optimizer.state_dict()
        torch.save(d, path_to_pt) 

    def load(self, path_to_pt, optimizer=None):
        if not os.path.exists(path_to_pt):
            print('Loading {weight_path} : error')
        else:
            if torch.cuda.is_available():
                data = torch.load(path_to_pt)
            else:
                data = torch.load(path_to_pt, map_location=lambda storage, loc: storage)

            self.patch_embedding.load_state_dict(data["patch_embedding"])
            self.fc.load_state_dict(data['fc'])
            self.epoch = data['epoch']
            if optimizer is not None:
                optimizer.load_state_dict(data['optimizer'])
            return optimizer


class EfficientB0(Baseline):
    def __init__(self, num_classes, loss_fn, fc_type="deep"):
        super(EfficientB0, self).__init__(loss_fn)
        self.num_classes = num_classes
        self.fc_type = fc_type
        self.patch_embedding = self.get_patch_embedding()
        self.embedding = self.get_embedding()
        self.fc = self.get_fc()     

    def get_patch_embedding(self):
        cnn = timm.create_model('efficientnet_b0', pretrained=False)
        return nn.Sequential( *list(cnn.children())[:-2])
    
    def get_embedding(self):
        return nn.Sequential(nn.AdaptiveAvgPool2d((1,1)), nn.Flatten())

    def get_fc(self):
        if self.fc_type == 'deep':
            fc = nn.Sequential(nn.Linear(1280, 1024),
                                        nn.BatchNorm1d(1024,  momentum=0.1),
                                        nn.ReLU(),
                                        nn.Linear(1024, 1024),
                                        nn.BatchNorm1d(1024,  momentum=0.1),
                                        nn.ReLU(),
                                        nn.Linear(1024, self.num_classes))

        elif self.fc_type == 'shallow':
            fc = nn.Linear(1280, self.num_classes)
        else:
            raise ValueError(f"Wrong fc-type input {self.fc_type}")
        return fc


In [40]:
from torch.optim import SGD
from torch.nn import CrossEntropyLoss
import torch.nn as nn
import torch.nn.functional as F

In [41]:
net = EfficientB0(10,CrossEntropyLoss)
optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)

In [42]:
for epoch in range(2):  # loop over the dataset multiple times

    running_loss = 0.0
    for i, data in enumerate(trainloader, 0):
        # get the inputs; data is a list of [inputs, labels]
        inputs, labels = data

        loss, y_pred = net.train_step(inputs,labels,optimizer=optimizer)

        # print statistics
        running_loss += loss.item()
        if i % 2000 == 1999:    # print every 2000 mini-batches
            print(f'[{epoch + 1}, {i + 1:5d}] loss: {running_loss / 2000:.3f}')
            running_loss = 0.0

print('Finished Training')

AttributeError: 'CrossEntropyLoss' object has no attribute 'backward'

In [12]:
import pandas as pd
train_emm = pd.read_csv('./cifar-100_embedding.csv')

In [8]:
model = EfficientB0(1024,CrossEntropyLoss)

In [22]:
model.eval()
s=0
for i in range(50000):
    predict = model.predict(trainset.__getitem__(i)[0].view(-1,3,32,32))
    if int(torch.max(predict, 1)[1]) == train_emm.iloc[i,0]:
        s+=1
print(s/500)


KeyboardInterrupt: 

# 그냥 가져오는 것으로는 정확도가 낮다. 마지막 ReLU 때문인것처럼 보인다.

In [37]:
"""embeddings=[]
labels =[]

mpatch.eval()

for i in range(50000):
    embeddings.append(mpatch(trainset.__getitem__(i)[0].view(-1,3,32,32)))
    labels.append(trainset.__getitem__(i)[1])

embeddings = [ emm.detach().numpy()   for emm in embeddings  ]


print(type(embeddings))
print(len(labels))

embedding_vector = pd.DataFrame({"labels":labels  ,"embeddings": embeddings})
embedding_vector.to_csv("./cifar-100_embedding.csv")
"""