In [ ]:
#이 파일은 k_center.py 모듈이 잘 돌아가는지 확인하기 위함. 확인이 끝나면 삭제하겠습니다.

In [1]:
from k_center import Kcenter,Set_distance
import numpy as np
# 이미지 수 110개와 73개, 임베딩 벡터 크기 10
# center의 최대 반지름이 threshold 보다 작도록 k-center 구하기
vec_set1 = np.random.randn(110,10) 
vec_set2 = np.random.randn(73,10)
vec_set3 = np.random.randn(23,10)
vec_set4 = np.random.randn(323,10)
set_coll = [vec_set1,vec_set2, vec_set3, vec_set4]

kt = Kcenter(set_coll)
kt.distance_matrix()

aa,bb = kt.selectKcenter(threshold= 0.4)
print(aa)
print(bb)
"""
1. class set 간 거리 행렬 만들기
2. 거리행렬을 기반으로 Kcenter 만들기
"""

(0,)
(4,)
(8,)
(12,)
(16,)


IndexError: tuple index out of range

In [2]:
# 이미지 수 10개, 임베딩 벡터 크기 5
#k 값을 정하고 k-center 구하기
vec_set = np.random.randn(10,5) 
print(vec_set.shape)
kc = Kcenter(vec_set)
kc.k=4
aa,bb = kc.selectKcenter()
print(aa)
print(bb)

(10, 5)


Exception: Weights was not declared

NameError: name 'np' is not defined

In [5]:

np.linalg.norm((set1_mean-set2_mean),L)

Exception: k is 0. clustering is not possible. If you don't want to decide on k, change it to None.

In [4]:
kt.k

2

In [7]:
aaa =None
print(type(aaa))
if aaa is None:
    print("sss")

<class 'NoneType'>
sss


In [2]:
vec_set1 = np.random.randn(110,10) 
vec_set2 = np.random.randn(73,10) 
set_ds = Set_distance(vec_set1, vec_set2)

In [5]:
print(set_ds.make_L_matrix())
set_ds.simple_max_distance()

[[3.77653616 5.0205332  5.52082092 ... 4.82261337 2.24718166 5.626216  ]
 [5.06933221 3.8781709  4.87201256 ... 3.98225696 3.87229208 5.89331464]
 [5.06911239 4.31591609 4.54103131 ... 5.3860941  3.86919075 4.34717497]
 ...
 [4.06072473 3.71878202 3.7127267  ... 3.48433194 3.83366562 5.00940601]
 [4.97854804 4.87808707 4.37784704 ... 4.83482278 4.45864431 4.02598404]
 [4.17495889 5.05895412 5.37972248 ... 6.31528743 5.45157201 6.30775486]]


8.10939345832145

In [6]:
print(np.mean(vec_set1, axis=0))

[ 0.02739592  0.14751956  0.04519864 -0.0643218   0.07469275  0.00156702
  0.06731832  0.13825608  0.06579158  0.01470208]


In [4]:
print(set_ds.distance)

0.48624487630072305
